### ISSUE TITLE
Release 3.2.0

### ISSUE THREAD

**Issue by vorburger** [vorburger/ch.vorburger.exec#187]

**Comment by duttonw** [comment]
Thanks for the reminder about jdk versions uplift.

As for this module, it may be time to allow it to run on the last 2 latest LTS's.

- Java SE 11 (LTS) (Released 25th September 2018 , with open source support till, October 2027 for Amazon Corretto)
- Java SE 17 (LTS) (Released 14th September 2021, with opensource support till, October 2029 for Amazon Corretto)
- Java SE 21 (LTS) (Released 19th September 2023, with opensource support till, October 2030 for Amazon Corretto)

For systems I'm managing, now that Java 21 LTS is released.

I will be beginning to transition to that version as it gives the longest window to the next LTS as Struts 6.x.x now allows Java 8 - 21 in their cicd testing.

The other big pressure in 2024 is Spring Boot/Framework which now requires min 17 for their latest major version.

> Spring Framework 6.2.x: JDK 17-25 (expected)
> Spring Framework 6.1.x: JDK 17-23
> Spring Framework 6.0.x: JDK 17-21
> Spring Framework 5.3.x: JDK 8-21 (as of 5.3.26)

Ref:
https://en.wikipedia.org/wiki/Java_version_history
https://ci-builds.apache.org/job/Struts/job/Struts%20Core/job/master/377/flowGraphTable/
https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes

**Comment by vorburger** [comment]
@duttonw the v3.2.0 of this library (exec) will be built with `---release=11`.

The previous version had a bit of a 1.8 / 11 mess; [this](https://github.com/vorburger/ch.vorburger.exec/commit/d4ea21ce64316c20aa720a946c3b72e04c3a863f) just fixed & cleaned it. 

Does that answer above? Would you like to contribute a PR for "matrix testing / building" this library against several Java versions [in its CI configuration](https://github.com/vorburger/ch.vorburger.exec/blob/main/.github/workflows/maven.yml)? I'm all for it! (But don't have the time / am too lazy to invest time into doing it myself.)

**Comment by vorburger** [comment]
I've just successfully deployed a 3.2.0 release to Maven Central.

https://github.com/vorburger/ch.vorburger.exec/compare/exec-3.1.5...exec-3.2.0 has the "release notes" (cough).

I'll be using this release for https://github.com/MariaDB4j/MariaDB4j/issues/918.

I'll close this issue based on that.

**Comment by duttonw** [comment]
Here you go: https://github.com/vorburger/ch.vorburger.exec/pull/192

I borrowed from my other repos: https://github.com/qld-gov-au/seleniumHelper/blob/main/.github/workflows/test.yml

**Comment by vorburger** [comment]
> https://github.com/vorburger/ch.vorburger.exec/compare/exec-3.1.5...exec-3.2.0 has the "release notes" (cough).

The most noteworthy change, which in itself justifies the major version upgrade, among others, is that https://github.com/vorburger/ch.vorburger.exec/issues/9 is fixed.
