### ISSUE TITLE
checkResult() should be optional

### ISSUE THREAD

**Issue by vorburger** [vorburger/ch.vorburger.exec#45]
The `waitForExit()` methods currently internally (all?) use `checkResult()`.

This makes it impossible to wait for a non-sucessful exit - which could be handy for some use cases (e.g. a CLI testing tool).

**Comment by mihneagiurgea** [comment]
I think we're running into this issue. I suspect that the following is happening:
```
ManagedProcess process = builder.build();
process.start(); // --> This fails due to some external factor, unknown at the time
process.waitForExit(); // -> This crashes with the error below, due to the cause you mentioned
```

`waitForExit` fails with this:
```
Caused by: ch.vorburger.exec.ManagedProcessException: Asked to waitFor Program [/tmp/75968747865555/MysqlDB4j/base/bin/mysql, -uroot, --socket=/tmp/75968747865555/MysqlDB4j.33803.sock] (in working directory /tmp/75968747865555/MysqlDB4j/base), but it was never even start()'ed! |
  |   | at ch.vorburger.exec.ManagedProcess.waitForExitMaxMsWithoutLog(ManagedProcess.java:439) |  
  |   | at ch.vorburger.exec.ManagedProcess.waitForExit(ManagedProcess.java:418) |  
  |   | at com.airbnb.mysql4j.DB.run(DB.java:405) |  
  |   | at com.airbnb.mysql4j.DB.run(DB.java:374) |  
  |   | at com.airbnb.mysql4j.DB.run(DB.java:357) |  
  |   | at com.airbnb.mysql4j.DB.run(DB.java:365) |  
  |   | at com.airbnb.mysql4j.DB.dropDB(DB.java:418) |  
  |   | at com.airbnb.mysql4j.DB.start(DB.java:181)
```

**Comment by vorburger** [comment]
@mihneagiurgea your #47 is a "bug" where an external process which is expected to exit with 0 (`mysqld`) is handled wrong. I suspect #96 actually fixed that problem.

This issue however is an "enhancement" to make this library usable to `exec` something which one is expecting (!) to have a non-zero exit code. One example of this is my use of this library for the [Executable Markdown](https://docs.enola.dev/use/execmd/) of Enola.dev, notably to avoid this (very) [ugly initial workwaround](https://github.com/enola-dev/enola/blob/460146c9dadde8d1dbab0b22fd2769f88e7ed8e2/common/markdown/src/main/java/dev/enola/common/markdown/exec/VorburgerExecRunner.java#L52).
