### ISSUE TITLE
Release 3.1.0 ?

### ISSUE THREAD

**Issue by vorburger** [vorburger/ch.vorburger.exec#7]
@duttonw was there anything else you wanted to contribute here before I release, other than #5 ? If not, I'll wip up a short summary of all recent commit in CHANGES.md (or you can?), and push current master as a 3.1.0 to Maven central...

**Comment by duttonw** [comment]
Since my input was to get a pull request across the line, I'm ok with this going forward. so we unblock MariaDB4j's pull request..

**Comment by vorburger** [comment]
@duttonw I've just pushed ch.vorburger.exec v3.1.0 to Maven central, and it should appear there shortly (minutes or some time max. a few hours). Can I let you see if it's all good?
