### ISSUE TITLE
Is there a way to shutdown internal executor manually?

### ISSUE THREAD

**Issue by kromar777** [vorburger/ch.vorburger.exec#95]
I'd like the started process alive after my application exits. It's an ip-phone that once started should keep running. But jvm cannot exit until I close the started process.

**Comment by vorburger** [comment]
@kromar777 this depends on the OS (Linux? Windows?) and how exactly you launch it.

Have you considered exec-ing something like `/usr/bin/bash -c 'your-ip-phone &'` - if you know what I mean? That might work.

Best of luck!
