### ISSUE TITLE
THREAD_SAFETY_VIOLATION (from Sonatype Lift)

### ISSUE THREAD

**Issue by vorburger** [vorburger/ch.vorburger.exec#99]
[Sonatype Lift raised](https://github.com/vorburger/ch.vorburger.exec/pull/96/files#r1126571313) a `THREAD_SAFETY_VIOLATION` in `ManagedProcess#assertWaitForIsValid()`  :

THREAD_SAFETY_VIOLATION: Read/Write race. Non-private method `ManagedProcess.assertWaitForIsValid()` indirectly reads without synchronization from `this.isAlive`. Potentially races with write in method `ManagedProcess.startExecute()`.
Reporting because another access to the same memory occurs on a background thread, although this access may not.

@cardamon is this the sort of thing you would enjoy contributing a fix for?

I'm hesitant whether or not to already merge your PR #96 as-is. Thoughts?

**Comment by mosesn** [comment]
I would vote for merging in #96 as-is since it doesn't make the problem worse AFAICT.

**Comment by vorburger** [comment]
The issue on Sonatype Lift is now gone.

Closing this as fixed by #103.
